baseURL = "https://code.justinmarciszewski.me/"
languageCode = "en-us"
title = "Justin Marciszewski"
theme = "hermit-v2"
enableRobotsTXT = true
googleAnalytics = "G-YWFFDZKCSJ"

publishDir = "docs"

[params]
  homeSubtitle = "My code website"
  readTime = true
  code_copy_button = true
  scrollToTop = true

[[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menus.main]]
  name = "Github"
  url = "https://github.com/justinjm/"
  weight = 30

[[menus.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/justinmarciszewski/"
  weight = 40

[[menus.main]]
  name = "Personal Site"
  url = "https://www.justinmarciszewski.me"
  weight = 50
