baseURL = "https://code.justinmarciszewski.me/"
languageCode = "en-us"
title = "Justin Marciszewski"
theme = "hermit-v2"
enableRobotsTXT = true

publishDir = "docs" # for github pages, need to be root or this dir

[services]
#  [services.disqus]
#    shortname = ''
  [services.googleAnalytics]
    id = 'G-YWFFDZKCSJ'


[params]
  homeSubtitle = "My code website"
  homeSubtitlePrinter = true
  readTime = true
  code_copy_button = true
  scrollToTop = true
  themeColor = "#494f5c"
  accentColor = "#018472"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/justinmarciszewski"

  [[params.socialLinks]]
    name = "x"
    url = "https://twitter.com/hianalytics"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/justinjm"



[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menus.main]]
  name = "Code"
  url = "/code/"
  weight = 20
